### ISSUE TITLE
您好,您生成的数据如何进行分析?

### ISSUE THREAD

**Issue by TheSeanParker** [i2Nav-WHU/KF-GINS#10]

**Comment by wang-lq** [comment]
我们提供的数据都有高精度参考真值，包括位置、速度和姿态参考结果。可以将生成的数据跟参考结果作差，求出定位结果的误差来评估定位精度。此外kf-gins还能输出估计的IMU传感器误差，可以观察传感器误差来判断组合导航的收敛情况。
