### ISSUE TITLE
Issue about GNSS interference

### ISSUE THREAD

**Issue by YoungCapta1n** [i2Nav-WHU/KF-GINS#11]
The struct of GNSS is defined as follows,
```
struct GNSS {
  double time;

  Eigen::Vector3d blh;
  Eigen::Vector3d std;

  bool isvalid;
};
```
If there is GNSS interference, the `isvalid` of GNSS return `false`. How to consider these problems in the GNSS-INS integrated system? Thanks!

**Comment by wang-lq** [comment]
The invalid GNSS data will not be used in the GNSS-INS integrated system.
