### ISSUE TITLE
In z axis of velocity in kf-gins dataset has negative values

### ISSUE THREAD

**Issue by mayankpatel97** [i2Nav-WHU/KF-GINS#14]
why z axis of velocity in kf-gins dataset  has negative values?
May I know to the alignment of IMU ?

-0.0495m/s   /   0.005s = -9.9m/s^2

![image](https://github.com/i2Nav-WHU/KF-GINS/assets/92679540/afa54a06-3f11-43a0-bd99-20c6ef1c8f39)

**Comment by iceberg1369** [comment]
Because IMU face in downward. ie on the bottom side of PCB

**Comment by mayankpatel97** [comment]
Thanks for the response

**Comment by mayankpatel97** [comment]
Hello, I am seeing a continuous drift in yaw angle. It starts from zero and then it keeps changing in one direction ( the device is in stationary state). When started the yaw angle was zero, and then after that the values starts dropping.. in the duration of 2-3 minutes , it dropped to 260 degree from 359 degree. What could be possible issue?  roll and yaw angles are perfectly fine. Please suggest some solution .

**Comment by iceberg1369** [comment]
@mayankpatel97 the yaw angle tends to drift in time while pitch and roll is almost stable. pitch and roll angle in stationary mode is derived from accelerometer and gravity vector. while the yaw angle is calculated by integrating gyroscope data. gyroscope data has intrinsic errors like bias and noise. in your case, you need to apply some ZUPT method in stationary mode

**Comment by mayankpatel97** [comment]
@iceberg1369  Okay .. Thanks .. Is there any reference document or code available online ?
