### ISSUE TITLE
IMU数据准备

### ISSUE THREAD

**Issue by JIXN123** [i2Nav-WHU/KF-GINS#15]
您好我有几个问题想请教一下
1、由于IMU在车上安装的位置不定，如果安装位置没有与载体对齐，安装误差会产生算法层面的误差吗？
2、当把输出速率转化为增量输入算法时，需要先对产品手册中描述的零偏进行补偿吗？

**Comment by wang-lq** [comment]
1, IMU和载体没有对齐不影响KF-GINS的使用，因为KF-GINS不涉及车辆运动信息辅助，所以不需要考虑IMU与车辆的相对安装参数；
2，产品手册里面应该不会给出常值零偏参数，即使能获取IMU常值零偏，也可以不用补偿，KF-GINS会对IMU零偏进行在线估计。
