### ISSUE TITLE
Add support to use velocity as input values

### ISSUE THREAD

**Issue by iceberg1369** [i2Nav-WHU/KF-GINS#17]
Sice velocity is more accurate measurment in gnss devices. I think this feature will lead to accurate attitude in navigation result despite having positions with high errors.

**Comment by wang-lq** [comment]
We will consider it in the following update.

**Comment by iceberg1369** [comment]
I would like to know is there any update planned for next release?

**Comment by wang-lq** [comment]
There will be no new version released recently to add velocity updates. You can refer to some literature on implementing the velocity update algorithm.

Page 97 on Estimation technology of low-cost inertial navigation [chrome-extension://cdonnmffkdaoajfknoeeecmchibpmkmg/assets/pdf/web/viewer.html?file=https%3A%2F%2Fwww.ucalgary.ca%2Fengo_webdocs%2FNES%2F05.20219.EHShin.pdf]






-----原始邮件-----
发件人:"Jeff Habibi" ***@***.***>
发送时间:2024-07-20 15:55:11 (星期六)
收件人: i2Nav-WHU/KF-GINS ***@***.***>
抄送: "Wang Liqiang" ***@***.***>, "State change" ***@***.***>
主题: Re: [i2Nav-WHU/KF-GINS] Add support to use velocity as input values (Issue #17)






I would like to know is there any update planned for next release?
