### ISSUE TITLE
How to Identify Yaw Angle Drift? What are the Key Parameters to Monitor in the Code ?

### ISSUE THREAD

**Issue by mayankpatel97** [i2Nav-WHU/KF-GINS#18]
Thank you for open-sourcing this excellent code.

I've implemented modifications to KF-GINS to ensure compatibility with the STM32 Microcontroller at my end. The code now effectively processes sensor inputs and executes the Kalman process in real-time, functioning seamlessly.

I do have a specific inquiry. When the device remains in a static state for several minutes, there is noticeable drift in the Yaw angle, which is expected given its reliance on a 6DoF system. And, EKF corrects this drift when the device is in motion.

To identify whether the yaw angle has drifted, which parameters should I monitor in the code?

**Comment by iceberg1369** [comment]
@mayankpatel97 the only way you have to invalidate yaw angle in stillness mode, you have to consider yaw angle inaccurate after 120 seconds . The other way is to implement zero-velocity algorithm.  By the wayCould you please share your stm32 implemented project?

**Comment by YoungCapta1n** [comment]
> @mayankpatel97 the only way you have to invalidate yaw angle in stillness mode, you have to consider yaw angle inaccurate after 120 seconds . The other way is to implement zero-velocity algorithm. By the wayCould you please share your stm32 implemented project?

Thank you for providing this excellent code about GINS. I have performed some movement test using the KF-GINS, based on dual-antenna GNSS and MEMS IMU. It can be seen from the following figures that some difference between GNSS heading and GINS heading. I was wondering that is this normal in the GNSS inertial results?

![Screenshot from 2024-03-26 17-28-23](https://github.com/i2Nav-WHU/KF-GINS/assets/23588051/14784865-1b9e-4926-ad88-59b179b20745)
![Screenshot from 2024-03-26 17-28-52](https://github.com/i2Nav-WHU/KF-GINS/assets/23588051/50745412-308f-4c23-882d-2daa485ec38e)

**Comment by iceberg1369** [comment]
@YoungCapta1n what gnss oem you used?

**Comment by YoungCapta1n** [comment]
> @YoungCapta1n what gnss oem you used?

Unistrong V28U

**Comment by iceberg1369** [comment]
@YoungCapta1n is your dataset IMU and GNSS data synchronized?

**Comment by YoungCapta1n** [comment]
> @YoungCapta1n is your dataset IMU and GNSS data synchronized?
I have reimplemented the code using C-99, and the KF-GINS loop have been shown in the following screen shot. I think the IMU and GNSS data are time synchronized. Maybe there is some errors in my code.

![Screenshot from 2024-03-27 15-23-28](https://github.com/i2Nav-WHU/KF-GINS/assets/23588051/957140bf-8697-40f1-b5fe-3f2186791c01)

**Comment by wang-lq** [comment]
For the single GNSS antenna configuration, the yaw angle is unobservable when the carrier is stationary or moving at a constant speed. Under these conditions, you can determine that the yaw angle will drift. However, for the double antenna configuration, GNSS can output yaw measurements and keep the yaw angle observable.
