### ISSUE TITLE
对于位置更新中，重新计算qne部分以及blh部分的解算不太理解，是否有对应的参考资料？代码部分和参考资料中给的不完全相同

### ISSUE THREAD

**Issue by bulangtuihuo** [i2Nav-WHU/KF-GINS#19]

**Comment by bulangtuihuo** [comment]
![image](https://github.com/i2Nav-WHU/KF-GINS/assets/61229256/1b1f682f-00af-4690-8ccf-0b0fbf51368a)

**Comment by wang-lq** [comment]
所提供的参考资料里面的位置更新，是通过n系下速度计算出n系下相对位置变化，然后转到大地坐标的相对位置进行位置更新，但是因为两个时刻位置不一样，n系是略有变化的，参考资料里面为了更新算法的清晰忽略了这个微小的变化。
代码实现的时候使用四元数形式更新，将两个时刻的位置通过一个不变的e系联系起来，考虑了这个n系的变化。
在常用载体上这两种方法都是可以使用的，而且不会体现出什么区别。
