### ISSUE TITLE
我现在想用我自己的imu数据和gnss数据替换工程中的Leador-A15.txt和GNSS-RTK.txt进行测试

### ISSUE THREAD

**Issue by shendward** [i2Nav-WHU/KF-GINS#20]
您好，请教您个问题：
1. 我现在采集了一份imu数据和gnss数据我分别命名为imu.txt和gnss.txt，数据的存储格式是按着Leador-A15.txt和GNSS-RTK.txt来的；
2. 我的imu输出的是三轴加速度和三轴角速度，频率是100Hz，我自己计算出了三轴速度增量和角度增量；
3. gnss.txt我只记录了经纬度和高程，最后三列的STD value我都填的是0，gnss的频率是10Hz；
4. 然后我修改了kf-gins.yaml文件，仅修改了如下几项：
- imupath和gnsspath指定为imu.txt和gnss.txt
- 将imudatarate修改为100
- 将starttime修改为imu.txt中的时间，不是imu.txt的第一条消息的时间而是仿照你的工程，是开始后几秒的一个时间。
- 将初始姿态initpos，修改为gnss.txt中starttime时刻的位置

如果我想用我自己的imu和gnss数据跑这个算法，具体我需要怎么做？希望得到您的指导，谢谢！

**Comment by Wanghang448** [comment]
请问您解决了吗？我用自己的数据集无法正确输出融合结果，只有前几秒有数据，后面全部是nan

**Comment by fymacle** [comment]
> 请问您解决了吗？我用自己的数据集无法正确输出融合结果，只有前几秒有数据，后面全部是nan

更改初始time值就好了，把结束的值改为-1
