### ISSUE TITLE
KF-GINS considering dual GNSS yaw measurement

### ISSUE THREAD

**Issue by YoungCapta1n** [i2Nav-WHU/KF-GINS#22]
Thanks for sharing the KF-GINS code. For the double antenna configuration, GNSS can output yaw measurements and keep the yaw angle observable. How to modify the measurement equations and code.

**Comment by thlsealight** [comment]
The yaw measurements from the GNSS is not considered in KF-GINS. Maybe you can refer to some papers, such as [Estimation](https://www.ucalgary.ca/engo_webdocs/NES/05.20219.EHShin.pdf).
