### ISSUE TITLE
融合结果中的yaw一直在递增？

### ISSUE THREAD

**Issue by lyk125** [i2Nav-WHU/KF-GINS#26]
hello:
    非常感谢开源的工程和课程！
     使用dataset里的数据运行后，发现融合后结果的yaw角度很奇怪，是在0~360之间循环，truth.nav里的yaw也是这样：
![yaw](https://github.com/user-attachments/assets/c9724427-0af7-4ff0-a536-cba9f5a1d628)
      这个如何理解呢？融合后结果的attitude angles (roll-pitch-yaw)的坐标系是哪个呢？
    期待您的答复!

regards

**Comment by wang-lq** [comment]
融合后的姿态角表示n系和b系之间的相对旋转，具体是表示n系分别按照Z轴、Y轴、X轴旋转航向角、俯仰角和横滚角后得到的坐标姿态（也就是b系）。欧拉角的具体定义请参考我们组开源姿态算法讲义。

**Comment by lyk125** [comment]
谢谢答复！但是我还是没有理解为什么yaw航向角一直在递增？麻烦指点下

**Comment by wang-lq** [comment]
你是说你用KF-GINS跑出来的航向一直在递增嘛？超过了0~360的范围？


-----原始邮件-----
发件人:lyk125 ***@***.***>
发送时间:2024-08-15 14:33:36 (星期四)
收件人: i2Nav-WHU/KF-GINS ***@***.***>
抄送: "Wang Liqiang" ***@***.***>, "State change" ***@***.***>
主题: Re: [i2Nav-WHU/KF-GINS] 融合结果中的yaw一直在递增？ (Issue #26)






谢谢答复！但是我还是没有理解为什么yaw航向角一直在递增？麻烦指点下

**Comment by lyk125** [comment]
是的，我看到真值truth.nav里的yaw角也是在一直递增，在0~360之间循环
![image](https://github.com/user-attachments/assets/68fd0588-0906-4a3d-a5f9-270e5ce5753c)

**Comment by wang-lq** [comment]
yaw递增不是很正常吗，载体的航向在变化，航向角度增加的减小是正常的。你可以再观察一下，肯定还是有航向递减的现象的。发自我的 iPhone在 2024年8月19日，10:48，lyk125 ***@***.***> 写道：﻿
是的，我看到真值truth.nav里的yaw角也是在一直递增，在0~360之间循环
image.png (view on web)

**Comment by lyk125** [comment]
哦哦，明白了：是b系一直在运动，运动中方向在变，yaw在变换
