### ISSUE TITLE
Script or program to model IMU  noise

### ISSUE THREAD

**Issue by iceberg1369** [i2Nav-WHU/KF-GINS#4]
I think we are in need of script or app that could help users in calculating ARW VRW std etc.  many users does not use tbe same IMU  as project. I think it would be great if some script could facilate IMU error modeling.

**Comment by wang-lq** [comment]
You can inquire about the error parameters of an IMU from its datasheet and adjust them in your dynamic test.

**Comment by iceberg1369** [comment]
Most low cost IMU  datasheets provide noise in PSD and they do not include bias instability at all.

**Comment by wang-lq** [comment]
Then just acquire them from the Allan curve. There have been many open-sourced Allan variance projects now, you can find them on Github.
