### ISSUE TITLE
您好我想问一下IMU的安装误差的问题

### ISSUE THREAD

**Issue by Dennissy23** [i2Nav-WHU/KF-GINS#7]
我的IMU安装在车上的时候会有安装角，这种安装带来的误差似乎会导致我的解算结果不正确，想向您请教一下这种安装误差该如何避免呢

**Comment by iceberg1369** [comment]
This is a nice question.

**Comment by wang-lq** [comment]
Actually, the GNSS/INS integration algorithm has nothing to do with the IMU install angle. As long as you set the correct initial attitude in the config file, KF-GINS will output the correct navigation solutions.

**Comment by iceberg1369** [comment]
I think wrong initial attitude makes converging longer and has almost no effect on fusion accuracy in long term. Correct me if im wrong

**Comment by zhh2005757** [comment]
> 安装角误差一般是在航位推算里才会估计，例如INS/里程计融合，因为安装误差角就是对于车体坐标系而言的。GNSS/IMU通常只有杆臂需要估计。

**Comment by zvictorliu** [comment]
姿态估计是 IMU 相对于导航坐标系，要得到载体系相对于导航坐标系就加上这部分安装角旋转就好了；或者，初始姿态就加上这部分旋转，这样应该也是等价的？
