### ISSUE TITLE
How to understand the motion of n coordinate frame?

### ISSUE THREAD

**Issue by qingyangG** [i2Nav-WHU/KF-GINS#9]
In my opinion, once the navigation frame is created, its relative pose to earth frame is fixed. So, how to understand w_en or q_n(k)^n(k-1). Maybe thery are equal to 0 or  quternion(I)

**Comment by wang-lq** [comment]
The origin point is the position of the carrier, which the navigation result describes. As the carrier is moving, the n-frame is changing.
